# Site settings
page_title: Claudiu-Adrian Soimu - novacard.ro
description: Novacard profile for Claudiu-Adrian Soimu
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://adriansoimu.novacard.ro" # the base hostname & protocol for your site


# Identity
name: Claudiu-Adrian Soimu
title: Software Developer
company: RapidSolution


# Contacts
email: claudiu.soimu@gmail.com
phone: +40751018278
website:                                                   # https://your-website.ltd 


# Social settings
facebook_url: https://www.facebook.com/soimu.claudiuadrian               # https://facebook.com/username/
linkedin_url: https://www.linkedin.com/in/claudiu-adrian-s-aa761b102/    # https://www.linkedin.com/in/username
instagram_url:                                             # https://www.instagram.com/username
pinterest_url:                                             # https://pinterest.com/username
twitter_url:                                               # https://twitter.com/username
youtube_url:                                               # https://youtube.com/channel/channel-id
snapchat_url:                                              # https://snapchat.com/add/
whatsapp_url:                                              # https://wa.me/your-phone-number-with-country-prefix
tiktok_url:                                                # https://tiktok.com/@username
telegram_url:                                              # https://t.me/username
skype_url:                                                 # https://join.skype.com/invite/user-id
github_url:                                                # https://github.com/username
gitlab_url:                                                # https://gitlab.com/username


# Build settings
markdown: kramdown
